namespace AHK.DataAccess.OracleDataAccess
{
    public enum AHKDbType
    {
        BFile,
        Blob,
        Byte,
        Char,
        Clob,
        Date,
        Decimal,
        Double,
        Int16,
        Int32,
        Int64,
        IntervalDS,
        IntervalYM,
        Long,
        LongRaw,
        NChar,
        NClob,
        NVarchar2,
        Raw,
        RefCursor,
        Single,
        TimeStamp,
        TimeStampLTZ,
        TimeStampTZ,
        Varchar2,
        XmlType
    }
}